version: "3.7"
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=postgres"
      - "DB_CONNECTION=pgsql"
      - "DB_DATABASE=bcon"
      - "DB_USERNAME=bcon"
      - "DB_PASSWORD=123"
      - "MAIL_MAILER=smtp"
      - "MAIL_HOST=mailer"
      - "MAIL_PORT=1025"
    volumes:
      - ./:/var/www
    depends_on:
      - postgres

  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=postgres"
      - "DB_CONNECTION=pgsql"
      - "DB_DATABASE=bcon"
      - "DB_USERNAME=bcon"
      - "DB_PASSWORD=123"
      - "MAIL_MAILER=smtp"
      - "MAIL_HOST=mailer"
      - "MAIL_PORT=1025"
    volumes:
      - ./:/var/www
    tty: true
    depends_on:
      - postgres

  node:
    image: node:15.2.1-alpine3.10
    volumes:
    - ./:/var/www
    working_dir: /var/www
    tty: true

  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: bcon
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bcon
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data
    ports:
    - "54321:5432"

  mailer:
    image: mailhog/mailhog
    restart: always
    ports:
    - 1025:1025
    - 8025:8025
